---
title: "Lecture Video Outline"
author: "Jeremy Morris"
output:
  word_document: default
  html_document:
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

What do I want the course to be about?

* Good analytics starts with business strategy and goes from there
* Depending on your goals and objectives, you will make certain decisions about the data you collect and how you report

* Introduction/Chapter 1: The Business Analytics Model
    1. Why is data important - a personal story
    2. What is Business Analytics
    3. The Business Analytics Model
    4. Radio station example
    5. [Article](https://www.forbes.com/sites/brentdykes/2019/03/28/the-four-key-pillars-to-fostering-a-data-driven-culture/#d9995657d90e)
    6. [7 Ways to Fail](https://www.cio.com/article/3235959/7-sure-fire-ways-to-fail-at-data-analytics.html)
    6. [Tech Intro: Git/GitHub](https://www.youtube.com/watch?v=BCQHnlnPusY)
    7. Tech Intro: Docker (TBD)
    8. Lab 1: (TBD)
* Chapter 2: BA at the Strategic Level
    1. Business Analytics at the strategic level
    2. Link between strategy and the deployment of BA
    3. Strategy and BA: Four scenarios
    4. Which information do we prioritize
    5. Goal setting methods (OKR vs BSQ)
        * [OKR Video](https://www.youtube.com/watch?v=L4N1q4RNi9I)
    6. Analytics influencing strategy
        * [Moneyball](https://www.youtube.com/watch?v=rMJ2IcD_fFc)
    6. Lab 2: (TBD)
* Chapter 3: Develoment and Deployment of Information at the Functional Level
    1. Introduction
    1. Summerhouse example
    2. Establishing processes with the Rockart model
    4. Optimizing business process
    6. ~~Which process should we start with~~ May do a chapter overview here and explain why not doing this.
    7. Lab 3: (TBD)
* Chapter 4: BA at the Analytical Level
    1. Introduction to chapter
    2. Data, information and knowledge,
    3. Analyst's role in the business analytics model
    4. Three requirements analysts must meet
    5. Required competencies for the analyst
    6. Quantitative method summary
    9. Business requirements
* Chapter 5: BA at the Data Warehouse Level
    1. Why a data warehouse?
    2. Architecture and processes in a data warehouse
    3. Data Cleanliness
    4. DW: Functions, Components and Examples
    3. Tips and Techniques in Data Warehousing
    6. [MDM and DQ](https://www.youtube.com/watch?v=dspdToaROn8)
* Chapter 6: The Company's Collection of Source Data
    1. What are source systems?
    2. Which information is best
    3. More than one job
    4. Data quality
* Chapter 7: Structuring of a Business Analytics Competency Center
    1. Analytics Competency Center
    2. Why setup a BACC?
    3. Tasks and Competencies
    4. Centralized or Decentralized?
    5. When should a BACC be established?
    6. Applying the Analytical Factory Approach
* Chapter 8: Assessment and Prioritization of Business Analytics Projects
    1. Is it a strategic project?
    2. When projects run over several years
    3. When uncertainty is too big
    4. Projects as part of the bigger picture
* Chapter 9: Business Analytics in the Future
* Final Exam